export const BLOG_SORT_VISIBLE = "BLOG_SORT_VISIBLE"
export const BLOG_SORT_CHANGBLOGSORTS = "BLOG_SORT_CHANGBLOGSORTS"
export const BLOG_SORT_CHANGLISTS = "BLOG_SORT_CHANGLISTS"
export const BLOG_SORT_SETRECORD = 'BLOG_SORT_SETRECORD'
export const BLOG_SORT_CREATE = "BLOG_SORT_CREATE"
export const BLOG_SORT_DEL = "BLOG_SORT_DEL"
