export const BLOG_VISIBLE = "BLOG_VISIBLE"
export const BLOG_CHANGBLOGSORTS = "BLOG_CHANGBLOGSORTS"
export const BLOG_SETRECORD = 'BLOG_SETRECORD'
export const BLOG_CREATE = "BLOG_CREATE"
export const BLOG_DEL = "BLOG_DEL"
