
export const HOME_GETTAG = 'HOME_GETTAG'

export const HOME_GETSORT = 'HOME_GETSORT'
export const HOME_HOT_LIST = 'HOME_HOT_LIST'
export const HOME_GETBLOGLIST = 'HOME_GETBLOGLIST'

export const HOME_BLOG_DETAIL='HOME_BLOG_DETAIL'