export const TAG_VISIBLE = "TAG_VISIBLE"
export const TAG_CHANGETAGS = "TAG_CHANGETAGS"
export const TAG_SETRECORD = "TAG_SETRECORD"
export const TAG_LIST = "TAG_LIST"
export const TAG_ADD = "TAG_ADD"
export const TAG_DEL = "TAG_DEL"
